# Generated by Django 2.2.2 on 2020-12-12 18:24

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=40, verbose_name='Account')),
                ('credit', models.BooleanField(default=False, verbose_name='Credit')),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('EUR', 'EUR')], default='CAD', max_length=10, verbose_name='Currency')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('account_created_datetime', models.DateTimeField(default=tracker.models.current_datetime, verbose_name='Account Created DateTime')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('percent', models.IntegerField(verbose_name='Percent')),
                ('date_sent', models.DateField(verbose_name='Date Sent')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(max_length=40, verbose_name='Bill')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount')),
                ('frequency', models.CharField(max_length=100, verbose_name='Frequency')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=10, verbose_name='Mode')),
            ],
            options={
                'verbose_name': 'Mode',
                'verbose_name_plural': 'Modes',
            },
        ),
        migrations.CreateModel(
            name='PurchaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
                ('category_created_datetime', models.DateTimeField(default=tracker.models.current_datetime, verbose_name='Category Created DateTime')),
            ],
            options={
                'verbose_name': 'Purchase Category',
                'verbose_name_plural': 'Purchase Categories',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=tracker.models.current_date, verbose_name='Date')),
                ('time', models.CharField(default=tracker.models.current_time, max_length=20, verbose_name='Time (24 hr.)')),
                ('item', models.CharField(max_length=100, verbose_name='Item(s)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount')),
                ('amount_2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Amount 2')),
                ('description', models.TextField(blank=True, verbose_name='Details')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_1', to='tracker.PurchaseCategory', verbose_name='Category')),
                ('category_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_2', to='tracker.PurchaseCategory', verbose_name='Category 2')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_filter', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date_filter', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Filter Last Updated')),
                ('category_filter_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_1', to='tracker.PurchaseCategory', verbose_name='Category Filter 1')),
                ('category_filter_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_10', to='tracker.PurchaseCategory', verbose_name='Category Filter 10')),
                ('category_filter_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_2', to='tracker.PurchaseCategory', verbose_name='Category Filter 2')),
                ('category_filter_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_3', to='tracker.PurchaseCategory', verbose_name='Category Filter 3')),
                ('category_filter_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_4', to='tracker.PurchaseCategory', verbose_name='Category Filter 4')),
                ('category_filter_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_5', to='tracker.PurchaseCategory', verbose_name='Category Filter 5')),
                ('category_filter_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_6', to='tracker.PurchaseCategory', verbose_name='Category Filter 6')),
                ('category_filter_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_7', to='tracker.PurchaseCategory', verbose_name='Category Filter 7')),
                ('category_filter_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_8', to='tracker.PurchaseCategory', verbose_name='Category Filter 8')),
                ('category_filter_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_9', to='tracker.PurchaseCategory', verbose_name='Category Filter 9')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
            },
        ),
        migrations.CreateModel(
            name='AccountUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Value')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Account Timestamp')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Account Update',
                'verbose_name_plural': 'Account Updates',
                'ordering': ['-timestamp'],
            },
        ),
    ]
