# Generated by Django 2.2.2 on 2020-02-09 19:24

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('percent', models.IntegerField(verbose_name='Percent')),
                ('date_sent', models.DateField(verbose_name='Date Sent')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(max_length=30, verbose_name='Bill')),
                ('last_update_date', models.DateField(default=tracker.models.current_date, verbose_name='Last Update Date')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateField(default=tracker.models.current_date, verbose_name='Last Update Date')),
                ('last_update_time', models.CharField(default=tracker.models.current_time, max_length=20, verbose_name='Time (24 hr.)')),
                ('category_filter', models.CharField(max_length=20, verbose_name='Category Filter')),
                ('time_filter', models.CharField(max_length=20, verbose_name='Time Filter')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=tracker.models.current_date, verbose_name='Date')),
                ('time', models.CharField(default=tracker.models.current_time, max_length=20, verbose_name='Time (24 hr.)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('item', models.CharField(max_length=100, verbose_name='Item(s)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
