# Generated by Django 2.2.2 on 2020-12-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-date_sent', 'type'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-amount'], 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='purchasecategory',
            options={'ordering': ['id'], 'verbose_name': 'Purchase Category', 'verbose_name_plural': 'Purchase Categories'},
        ),
        migrations.AddField(
            model_name='accountupdate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Exchange Rate'),
        ),
    ]
