# Generated by Django 2.2.2 on 2020-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201212_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountupdate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Exchange Rate to CAD'),
        ),
    ]
