# Generated by Django 2.2.2 on 2020-02-12 23:25

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_purchase_category_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='last_update_time',
            field=models.CharField(default=tracker.models.current_time, max_length=30, verbose_name='Time (24 hr.)'),
        ),
    ]
