# Generated by Django 2.2.2 on 2020-02-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200212_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=10, verbose_name='Mode')),
            ],
            options={
                'verbose_name': 'Mode',
                'verbose_name_plural': 'Modes',
            },
        ),
    ]
