# Generated by Django 2.2.2 on 2020-12-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20201212_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('EUR', 'EUR')], default='CAD', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Exchange Rate to CAD'),
        ),
        migrations.AlterField(
            model_name='accountupdate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Exchange Rate to CAD'),
        ),
    ]
