# Generated by Django 2.2.2 on 2020-02-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='deactivate',
            field=models.CharField(default='No', max_length=5, verbose_name='Deactivate'),
        ),
    ]
