# Generated by Django 2.2.2 on 2020-12-13 11:07

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20201213_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Exchange Rate to CAD'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.CharField(default=tracker.models.current_time, max_length=5, verbose_name='Time (24 hr.)'),
        ),
    ]
