# Generated by Django 2.2.2 on 2020-02-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_filter_deactivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='deactivate',
        ),
        migrations.AddField(
            model_name='filter',
            name='deactivate_category',
            field=models.CharField(default='No', max_length=5, verbose_name='Deactivate Category'),
        ),
        migrations.AddField(
            model_name='filter',
            name='deactivate_time',
            field=models.CharField(default='No', max_length=5, verbose_name='Deactivate Time'),
        ),
    ]
