# Generated by Django 2.2.2 on 2020-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20201213_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecategory',
            name='threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Threshold'),
        ),
        migrations.AddField(
            model_name='purchasecategory',
            name='threshold_rolling_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Threshold Rolling Days'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Account Created DateTime'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='percent',
            field=models.PositiveIntegerField(verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='purchasecategory',
            name='category_created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Category Created DateTime'),
        ),
    ]
