# Generated by Django 2.2.2 on 2020-12-15 20:18

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20201213_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.CharField(blank=True, default=tracker.models.current_time, max_length=5, verbose_name='Time (24 hr.)'),
        ),
    ]
