# Generated by Django 2.2.2 on 2020-12-18 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20201215_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='category_filter_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_11', to='tracker.PurchaseCategory', verbose_name='Category Filter 11'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_12', to='tracker.PurchaseCategory', verbose_name='Category Filter 12'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_13', to='tracker.PurchaseCategory', verbose_name='Category Filter 13'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_14', to='tracker.PurchaseCategory', verbose_name='Category Filter 14'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_15', to='tracker.PurchaseCategory', verbose_name='Category Filter 15'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_16', to='tracker.PurchaseCategory', verbose_name='Category Filter 16'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_17', to='tracker.PurchaseCategory', verbose_name='Category Filter 17'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_18', to='tracker.PurchaseCategory', verbose_name='Category Filter 18'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_19', to='tracker.PurchaseCategory', verbose_name='Category Filter 19'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_20', to='tracker.PurchaseCategory', verbose_name='Category Filter 20'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_21', to='tracker.PurchaseCategory', verbose_name='Category Filter 21'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_22', to='tracker.PurchaseCategory', verbose_name='Category Filter 22'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_23', to='tracker.PurchaseCategory', verbose_name='Category Filter 23'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_24', to='tracker.PurchaseCategory', verbose_name='Category Filter 24'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_25', to='tracker.PurchaseCategory', verbose_name='Category Filter 25'),
        ),
    ]
