# Generated by Django 2.2.2 on 2020-12-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_purchasecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Amount 2'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
    ]
