# Generated by Django 2.2.2 on 2020-12-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20201219_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount')),
                ('frequency', models.CharField(max_length=100, verbose_name='Frequency')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Recurring',
                'verbose_name_plural': 'Recurrings',
                'ordering': ['-amount'],
            },
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
