# Generated by Django 2.2.2 on 2020-12-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20201220_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='receipt',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
