# Generated by Django 2.2.2 on 2020-12-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_purchase_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Receipt'),
        ),
    ]
