# Generated by Django 2.2.2 on 2020-12-07 19:38

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20201206_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Account')),
                ('account_created_datetime', models.DateTimeField(default=tracker.models.current_datetime, verbose_name='Account Created DateTime')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.AlterField(
            model_name='purchasecategory',
            name='category',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Category'),
        ),
    ]
