# Generated by Django 2.2.2 on 2020-12-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20201229_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring',
            name='description',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
    ]
