# Generated by Django 2.2.2 on 2020-12-31 17:45

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_recurring_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring',
            name='frequency',
        ),
        migrations.AddField(
            model_name='recurring',
            name='days',
            field=models.CharField(blank=True, max_length=100, verbose_name='Days'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='interval_type',
            field=models.CharField(blank=True, choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], max_length=15, verbose_name='Interval Type'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='start_date',
            field=models.DateField(default=tracker.models.current_date, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='weekdays',
            field=models.CharField(blank=True, max_length=100, verbose_name='Weekdays'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='xth_after_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Xth After Months'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='xth_after_specific_date',
            field=models.DateField(blank=True, null=True, verbose_name='Xth After Specific Date'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='xth_mode',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Specific', 'Specific')], max_length=15, verbose_name='Xth Mode'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='xth_type',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Weekday', 'Weekday'), ('Weekend', 'Weekend')], max_length=15, verbose_name='Xth Type'),
        ),
    ]
