# Generated by Django 2.2.2 on 2020-12-07 20:12

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20201207_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='AccountUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Value')),
                ('timestamp', models.DateTimeField(default=tracker.models.current_datetime, verbose_name='Account Timestamp')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.PurchaseCategory', verbose_name='Account')),
            ],
            options={
                'verbose_name_plural': 'Account Updates',
            },
        ),
    ]
