# Generated by Django 2.2.2 on 2021-01-01 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0015_auto_20201231_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('EUR', 'EUR')], default='CAD', max_length=10, verbose_name='Primary Currency')),
                ('secondary_currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('EUR', 'EUR')], default='EUR', max_length=10, verbose_name='Secondary Currency')),
                ('account_to_use', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_1', to='tracker.Account', verbose_name='Account to Use')),
                ('credit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_2', to='tracker.Account', verbose_name='Credit Account')),
                ('debit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_3', to='tracker.Account', verbose_name='Debit Account')),
                ('secondary_debit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_4', to='tracker.Account', verbose_name='Secondary Debit Account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
        migrations.AlterField(
            model_name='accountupdate',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_updates', to='tracker.Account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_1', to='tracker.PurchaseCategory', verbose_name='Category Filter 1'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_10', to='tracker.PurchaseCategory', verbose_name='Category Filter 10'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_11', to='tracker.PurchaseCategory', verbose_name='Category Filter 11'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_12', to='tracker.PurchaseCategory', verbose_name='Category Filter 12'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_13', to='tracker.PurchaseCategory', verbose_name='Category Filter 13'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_14', to='tracker.PurchaseCategory', verbose_name='Category Filter 14'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_15', to='tracker.PurchaseCategory', verbose_name='Category Filter 15'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_16', to='tracker.PurchaseCategory', verbose_name='Category Filter 16'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_17', to='tracker.PurchaseCategory', verbose_name='Category Filter 17'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_18', to='tracker.PurchaseCategory', verbose_name='Category Filter 18'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_19', to='tracker.PurchaseCategory', verbose_name='Category Filter 19'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_2', to='tracker.PurchaseCategory', verbose_name='Category Filter 2'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_20', to='tracker.PurchaseCategory', verbose_name='Category Filter 20'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_21', to='tracker.PurchaseCategory', verbose_name='Category Filter 21'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_22', to='tracker.PurchaseCategory', verbose_name='Category Filter 22'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_23', to='tracker.PurchaseCategory', verbose_name='Category Filter 23'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_24', to='tracker.PurchaseCategory', verbose_name='Category Filter 24'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_25', to='tracker.PurchaseCategory', verbose_name='Category Filter 25'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_3', to='tracker.PurchaseCategory', verbose_name='Category Filter 3'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_4', to='tracker.PurchaseCategory', verbose_name='Category Filter 4'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_5', to='tracker.PurchaseCategory', verbose_name='Category Filter 5'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_6', to='tracker.PurchaseCategory', verbose_name='Category Filter 6'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_7', to='tracker.PurchaseCategory', verbose_name='Category Filter 7'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_8', to='tracker.PurchaseCategory', verbose_name='Category Filter 8'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_9', to='tracker.PurchaseCategory', verbose_name='Category Filter 9'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_1', to='tracker.PurchaseCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_2', to='tracker.PurchaseCategory', verbose_name='Category 2'),
        ),
        migrations.AlterField(
            model_name='recurring',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrings', to='tracker.Account', verbose_name='Account'),
        ),
    ]
