# Generated by Django 2.2.2 on 2020-12-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20201207_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountupdate',
            options={'verbose_name': 'Account Update', 'verbose_name_plural': 'Account Updates'},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='last_update_date',
        ),
        migrations.AddField(
            model_name='bill',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='bill',
            name='frequency',
            field=models.CharField(max_length=100, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Bill'),
        ),
    ]
