# Generated by Django 2.2.2 on 2020-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20201207_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='frequency',
            field=models.CharField(default='1', max_length=100, verbose_name='Frequency'),
        ),
    ]
