# Generated by Django 2.2.2 on 2020-12-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_remove_purchase_category_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.CharField(max_length=120, verbose_name='Item(s)'),
        ),
    ]
