# Generated by Django 2.2.2 on 2021-01-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20210102_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='page',
            field=models.CharField(choices=[('Homepage', 'Homepage'), ('Analysis', 'Analysis')], default='Homepage', max_length=20, verbose_name='Page'),
        ),
    ]
