# Generated by Django 2.2.2 on 2021-01-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_filter_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='page',
            field=models.CharField(choices=[('Homepage', 'Homepage'), ('Analysis', 'Analysis')], max_length=20, verbose_name='Page'),
        ),
    ]
