# Generated by Django 2.2.2 on 2021-01-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20210102_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='page',
            field=models.CharField(choices=[('Homepage', 'Homepage'), ('Activity', 'Activity')], default='Activity', max_length=20, verbose_name='Page'),
        ),
    ]
