# Generated by Django 2.2.2 on 2020-12-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20201207_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='category_filter',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='deactivate_category',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='deactivate_time',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='last_update_date',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='last_update_time',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='time_filter',
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_1', to='tracker.PurchaseCategory', verbose_name='Category Filter 1'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_10', to='tracker.PurchaseCategory', verbose_name='Category Filter 10'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_2', to='tracker.PurchaseCategory', verbose_name='Category Filter 2'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_3', to='tracker.PurchaseCategory', verbose_name='Category Filter 3'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_4', to='tracker.PurchaseCategory', verbose_name='Category Filter 4'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_5', to='tracker.PurchaseCategory', verbose_name='Category Filter 5'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_6', to='tracker.PurchaseCategory', verbose_name='Category Filter 6'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_7', to='tracker.PurchaseCategory', verbose_name='Category Filter 7'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_8', to='tracker.PurchaseCategory', verbose_name='Category Filter 8'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category_filter_9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_9', to='tracker.PurchaseCategory', verbose_name='Category Filter 9'),
        ),
        migrations.AddField(
            model_name='filter',
            name='end_date_filter',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='filter',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Filter Last Updated'),
        ),
        migrations.AddField(
            model_name='filter',
            name='start_date_filter',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
