# Generated by Django 2.2.2 on 2021-01-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_auto_20210103_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickentry',
            options={'verbose_name': 'Quick Entry', 'verbose_name_plural': 'Quick Entries'},
        ),
    ]
