# Generated by Django 2.2.2 on 2021-01-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_auto_20210103_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurring',
            options={'ordering': ['-amount'], 'verbose_name': 'Recurring Payment', 'verbose_name_plural': 'Recurrings Payments'},
        ),
    ]
