# Generated by Django 2.2.2 on 2020-12-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_auto_20201208_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountupdate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Account Timestamp'),
        ),
    ]
