# Generated by Django 2.2.2 on 2021-01-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_auto_20210103_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring',
            name='days',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='xth_mode',
        ),
        migrations.AddField(
            model_name='recurring',
            name='dates',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dates'),
        ),
    ]
