# Generated by Django 2.2.2 on 2020-12-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20201208_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit',
            field=models.BooleanField(default=False, verbose_name='Credit'),
        ),
    ]
