# Generated by Django 2.2.2 on 2021-01-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20210104_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='secondary_currency',
        ),
    ]
