# Generated by Django 2.2.2 on 2020-12-10 22:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_account_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountupdate',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Value'),
        ),
    ]
