# Generated by Django 2.2.2 on 2021-01-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_auto_20210105_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit (Bill)'), ('Debit', 'Debit (Income)')], max_length=20, verbose_name='Type'),
        ),
    ]
