# Generated by Django 2.2.2 on 2020-12-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_auto_20201210_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='category_filter_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_1', to='tracker.PurchaseCategory', verbose_name='Category Filter 1'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_10', to='tracker.PurchaseCategory', verbose_name='Category Filter 10'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_2', to='tracker.PurchaseCategory', verbose_name='Category Filter 2'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_3', to='tracker.PurchaseCategory', verbose_name='Category Filter 3'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_4', to='tracker.PurchaseCategory', verbose_name='Category Filter 4'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_5', to='tracker.PurchaseCategory', verbose_name='Category Filter 5'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_6', to='tracker.PurchaseCategory', verbose_name='Category Filter 6'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_7', to='tracker.PurchaseCategory', verbose_name='Category Filter 7'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_8', to='tracker.PurchaseCategory', verbose_name='Category Filter 8'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category_filter_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_9', to='tracker.PurchaseCategory', verbose_name='Category Filter 9'),
        ),
    ]
