# Generated by Django 2.2.2 on 2021-01-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_auto_20210105_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='interval_type',
            field=models.CharField(blank=True, choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], default='Days', max_length=15, verbose_name='Interval Type'),
        ),
    ]
