# Generated by Django 2.2.2 on 2021-01-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_auto_20210105_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrings_3', to='tracker.PurchaseCategory', verbose_name='Category'),
        ),
    ]
