# Generated by Django 2.2.2 on 2020-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_auto_20201210_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('EURO', 'EURO')], default='CAD', max_length=10, verbose_name='Currency'),
        ),
    ]
