# Generated by Django 2.2.2 on 2020-12-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('EUR', 'EUR')], default='CAD', max_length=10, verbose_name='Currency'),
        ),
    ]
