# Generated by Django 2.2.2 on 2020-12-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_auto_20201212_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
