# Generated by Django 2.2.2 on 2021-01-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_auto_20210107_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='xth_from_specific_date',
            field=models.CharField(blank=True, default=15, max_length=10, verbose_name='Xth From Specific Date'),
            preserve_default=False,
        ),
    ]
