# Generated by Django 2.2.2 on 2020-12-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_auto_20201212_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
