# Generated by Django 2.2.2 on 2021-01-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_auto_20210107_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='xth_type',
            field=models.CharField(blank=True, choices=[('Weekday', 'Weekday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Weekend', 'Weekend')], max_length=15, verbose_name='Xth Type'),
        ),
    ]
