# Generated by Django 2.2.2 on 2021-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_purchase_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Maximum Amount'),
        ),
        migrations.AddField(
            model_name='filter',
            name='date_to_exclude',
            field=models.DateField(blank=True, null=True, verbose_name='Date to Exclude'),
        ),
    ]
