# Generated by Django 2.2.2 on 2021-01-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_auto_20210110_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='pie_chart_mode',
            field=models.CharField(choices=[('Counts', 'Counts'), ('Sums', 'Sums')], default='Counts', max_length=10, verbose_name='Pie Chart Mode'),
        ),
    ]
