# Generated by Django 3.1.5 on 2021-01-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_filter_pie_chart_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='pie_chart_mode',
            field=models.CharField(choices=[('Counts', 'Counts'), ('Sums', 'Sums')], default='Counts', max_length=20, verbose_name='Pie Chart Mode'),
        ),
    ]
