# Generated by Django 3.1.5 on 2021-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0043_auto_20210115_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='xth_from_specific_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Xth From Specific Date'),
        ),
    ]
