# Generated by Django 3.1.5 on 2021-01-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0044_auto_20210117_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit (Bill)'), ('Debit', 'Debit (Income)')], default='Credit', max_length=20, verbose_name='Type'),
        ),
    ]
