# Generated by Django 3.1.5 on 2021-01-22 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0045_auto_20210119_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='category',
            field=models.ForeignKey(default='Bills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrings_3', to='tracker.purchasecategory', verbose_name='Category'),
        ),
    ]
